server:
  port: 8761

spring:
  application:
    name: eurekaServer
  profiles:
    active: prod

eureka:
  client:
    registerWithEureka: false #Eureka server 에 instance로 등록할지에 대한 여부
    fetchRegistry: false      #Registry 정보를 local cache에 저장할지에 대한 여부
  server:
    renewal-percent-threshold: 0.85
    renewal-threshold-update-interval-ms: 900000
    response-cache-update-interval-ms: 5000 #서버에서 캐시 업데이트 주기

# acuator 설정
management:
  endpoints:
    web:
      exposure:
        include: health